theme: jekyll-theme-cayman
title: "Discord Bots"
author: "PLSzymonGaming"
description: "The Best Discord Website For Bots!"
permalink: /:title/
lang: "en"
date_format: "%8 %d, %Y"

# layout

show_social: true
show_excerpts: false
show_frame: false
show_sidebar: false

# Menu

navigation:
  - {file: "index.html", title: "Bots", icon: home}
  
external:
  - {title: YouTube, icon: youtube, url: "https://www.youtube.com/c/SzymonGamingYT/"}
